### ISSUE TITLE
Suggestion: regex for selectable fields

### ISSUE THREAD

**Issue by instanceofme** [mptre/yank#16]
With the seemingly canonical `ps` example, I'd like to be able to limit the selectable fields to PIDs, so maybe only numbers. Instead of specifying a selector, I'd give a regex (preferably PCRE):

``` shell
ps | yank -r '\b\d+\b' | xargs kill
```

`yank` would then only go through number fields.

What do you think?

**Comment by mptre** [comment]
Interesting idea that also crossed my mind. The current implementation looks at
every byte in order to determine if it's a delimiter or not. One possible
solution in order to support both the current `-d' option and`-r' would be to
always use regular expressions internally. This might actually lead to a
reduction of #LOC which I find tempting.

Your `ps' example is a great use case. You can get quite creative with regular
expressions. Here's another idea: match file and line numbers from a compiler
output and open up your editor of choice with the erroneous file and line:

  OPTS=$(make 2>&1
         | yank -r '^[^:]+:[[:digit:]]+'
         | awk -F : '{print "-t", $2, $1}')

  $EDITOR $OPTS

I will definitely look into this!

**Comment by mptre** [comment]
Update: since the support for arrow key bindings is now in testing I'm going to start implementing support for regex.

**Comment by mptre** [comment]
See the new regex branch[1].

[1] https://github.com/mptre/yank/pull/20
