### ISSUE TITLE
Suggestion: option to auto-select single field

### ISSUE THREAD

**Issue by instanceofme** [mptre/yank#17]
If there is only one single field (or one line in `-l` mode), have an option (e.g. `-y`) to skip the interactive part and just proceed with the only value. This of course shouldn't be the default (least surprise / consistency, ability to Ctrl-C, etc.) but could be useful in some situations.

My use case: kill a specific java program. I want to choose if there are more than one running but directly kill when there is only one. So something like this:

``` shell
jps | fgrep MyMainClass | yank -y | xargs kill
```

On a related note, when there is no input (e.g. no matching running java process in the example above), no output / error is displayed but the interactive mode is still active, which can be confusing. Is there a reason not to show a warning on stderr?  
In this empty-input case, I would expect `-y` to proceed with empty value (e.g. for `pbcopy` and it doesn't disturb `xargs`) but keep the warning.

**Comment by instanceofme** [comment]
Con: maybe that's increasing #LOC for little effet, since it only saves one Enter keystroke.

**Comment by mptre** [comment]
The auto select if only one field is present is not the intentional
behaviour of yank. This functionality could easily be implement with a few
lines of shell scripting. The script below is a rough outline, caution not
tested:

  P=$(jps | fgrep "$1")

  if [ $(echo "$P" | wc -l) -gt 1 ]; then
    echo "$P" | yank | xargs kill
  else
    # Get the PID from $P and invoke kill
  fi

Some kind of output when the input is empty sounds like a good idea.
Mimicking less (less </dev/null) with a end marker might be a solution.

On 26 October 2015 at 11:33, Adrien Lavoillotte notifications@github.com
wrote:

> If there is only one signle field (or one line in -l mode), have an
> option (e.g. -y) to skip the interactive part and just proceed with the
> only value. This of course shouldn't be the default (least surprise /
> consistency, ability to Ctrl-C, etc.) but could be useful in some
> situations.
> 
> My use case: kill a specific java program. I want to choose if there are
> more than one running but directly kill when there is only one. So
> something like this:
> 
> jps | fgrep MyMainClass | yank -y | xargs kill
> 
> On a related note, when there is no input (e.g. no matching running java
> process in the example above), no output / error is displayed but the
> interactive mode is still active, which can be confusing. Is there a reason
> not to show a warning on stderr?
> 
> In this empty-input case, I would expect -y to proceed with empty value
> (e.g. for pbcopy and it doesn't disturb xargs) but keep the warning.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mptre/yank/issues/17.

## 

:wq

**Comment by mptre** [comment]
After further thinking outputting some kind of warning/error on stderr when the input is empty doesn't feel justified to me since it's not an error per se. Many common Unix-utilities does not output anything when the input is empty. Therefore I'm closing this issue for now. Feel free to re-open if you want to continue the discussion.
