### ISSUE TITLE
Yank without yanking colors

### ISSUE THREAD

**Issue by netei** [mptre/yank#26]
Say some command has colored output, it should just copy the text and not the escape characters.

Sample : 
- `echo "$(tput setaf 1)foo$(tput sgr0) bar" | yank`
- Select foo
- If you paste foo, you get `mfoo`

**Comment by netei** [comment]
I've set 

`alias yank='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed "s/\x0f//g" | yank'`

which solves the problem, kind of , but the output is not colored anymore

**Comment by mptre** [comment]
Thanks for the report. However commands that is part of a chain of pipes
usually don't output ANSI escape sequence colors unless you explicitly
tell them to. Like the grep(1) `--color=always` option. If you still
want colors in the input sent to yank you could simply strip the yanked
field after. Notice yank command won't be invoked since the output is
piped, therefore the last call to xsel(1) is needed which of course
could be any command of your choice.

  alias yank='yank | sed -r "s/\x1B[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed "s/\x0f//g" | xsel'

On Tue, Feb 23, 2016 at 08:26:48AM -0800, netei wrote:

> I've set 
> 
> `alias yank='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed "s/\x0f//g" | yank'`
> 
> which solves the problem, kind of , but the output is not colored anymore
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mptre/yank/issues/26#issuecomment-187773177

## 

:wq

**Comment by netei** [comment]
I have some custom commands that always output colors, that's why I needed this.

Your trick to put the pipes after the yank is great, I didn't know that yank would output to stdout when it is piped.
