### ISSUE TITLE
Make yank not depend on `xsel`

### ISSUE THREAD

**Issue by Slackadays** [mptre/yank#67]
I noticed that `yank` is cross-platform and works with technically any clipboard utility. `yank` also defaults to `xsel` which depends on X11 and requires extra effort to switch over if you're using Wayland, macOS, Windows, etc or have a headless Linux/BSD server in which case you're toast. However, my project Clipboard works on all those platforms including headless Linux/BSD, so I think it might be worth it to default to `cb` instead of `xsel` so that users don't have to think about which platform they have in particular. Does this sound like a reasonable proposition?

**Comment by mptre** [comment]
On Thu, Feb 23, 2023 at 12:00:45PM -0800, Jackson Huff wrote:
> I noticed that `yank` is cross-platform and works with technically any clipboard utility. `yank` also defaults to `xsel` which depends on X11 and requires extra effort to switch over if you're using Wayland, macOS, Windows, etc or have a headless Linux/BSD server in which case you're toast. However, my project Clipboard works on all those platforms including headless Linux/BSD, so I think it might be worth it to default to `cb` instead of `xsel` so that users don't have to think about which platform they have in particular. Does this sound like a reasonable proposition?

clipboard seems to be more sophisticated than say xsel since it can
"sense" the host. However, it's also just another dependency.

You have to consider the bigger picture here in which yank is already
packaged for many Linux distributions and *BSDs. The package maintainer
have often already chosen a sensible default clipboard implementation[1]
(which can be defined at compile time). Meaning that in practice, yank
does "the right thing" on many platforms. Your concern seems more
related to building from source.

I will therefore have to pass on this.

[1] https://github.com/Homebrew/homebrew-core/blob/bc18192d5f01cfc11a569af66792fb5009e42674/Formula/yank.rb#L22
